[package]
name = "commit"
version = "0.1.0"
authors = [""]

[lib]
crate-type = ["cdylib"]

[profile.release]
panic = "abort"
lto = true

[workspace]
members = []

[dependencies]
serde="1"
serde_derive="1"
serde_json="1"
libc = "0.2.42"