language: rust
sudo: required
services:
  - docker
dist: trusty
addons:
  apt:
    packages:
    - libssl-dev
cache: cargo
rust:
  - stable
env:
  global:
    - secure: R6Qw8reHFKVTwziluSxv0Uq4FVfwOI7u0IhUloYjyOZIgWp5+0p0i6FvVB6W13RfEevbBusrl6GHaIe5mGsrLZSN5ICHnN1ZLVhaVnZzoQLGdojHzYBneR5yETogbNA1DiCRZBz62cefkDpfawbUPh8rZQLcO74vfbfFLm+Z838gnCZUhjcYuESHUpA1V3vgXUYuQKp8fVcOCODew0LzAFgbLvipuNZENbb6smyIJAHh8erE4vJdvosCNlMr8Dm5/IUMPYgCcTOjDEUmGt3SktXtrEhJFtMP2RDuSC59qRwQSqBYrdas7LoT7DwP9gh/cWnQtlZJzW3zxaOIWwRk6HiEp4Eds2nGa3j7PPN2WetKfQC6s0wBe9FGqXuQ0HXwlzpQ6+V41J+QraYZMfVRDrrCRAO0DCY2bG/n1T3NYg3PzOM4vLeC3fiLX/lfglpMhWtJ6B22Zm+07KqXHyenDOKHFVKckmISCnouszrD4ay3UC8f1+Xcvp9SvgOLdcPDMqTXyGGDsANzLpttT9wGafBRm+TOMNvMsqkm+EyfTYlsI7SUw1pDYvkg16N115E9V6z1oLdYkS2zbKP5HU0SIPR9kJ2fKQG703prZW9zijnspf9+4k2kyKs/bXfa5Md00DW1BsgfhwI0Fvt6oK8h69MSCaeQnDrWIe9C5sMYQsg=
    - secure: PGd7dK2ciu86Ej2JoEI7upwvRAhUhS3XJnFqCRO9ujKktGHiUXB1HzlarftLapBL4EJ4VkgtJkkdd70yn2kZyVCSElfF/xF6AE0JOcLK5DKn5mbp+qBMXqRYy+bbjveMq1FU2O/d2rmP4nYle5c026gp0AFm95h2h6et3b0+/AM53Is1a8fopMspPso88Nc3o8TT7ouNyrOYlxNN4M2rXbndQWmdfguXBasnidTpbMq7gCC/1H2yLHWj4dyqiDmpKZck+1zVKWBqJtbLrwEg97mQ3yMnmzX91jYMiEj00kPjXG121W3M1HIS2Mdiiz+3RW963aSKpp7gXAM9cprQHgbx2xFEdVrVAKbGH9FTVlpVDjkdBDAcHsJ9B+ygs6ML8byZQDSfVZBbDDwL8Kk2lgRCN+5TIyjEOzSOyD/3FjSO2LL2ccX7wIeo/dbhD2C0MwdkCLsH5TRvkz/C0d16XxTR9wn2bVlDNKcjIZFrgFj/R8//dJc049J39uRHJ88zK5jENPHisUEzVjCtIi2EHzQz87j8lBO6EVu+P1fc4s9CKGHGTBXMznBRfFym1M0rnqG+aXabjZ5fyS5qAfTIJyquNI9B9Enk154p07ALNIsDqozkEFwsMUCeq6/aZojl/SxcAgxT6oto2jCV1hl9Y6I/8fTqfMWOtHlbFh02qhk=
install:
  - rustup toolchain install nightly
  - rustup update
  - rustup component add rustfmt-preview --toolchain=nightly
  - cargo +nightly install clippy || echo "clippy already installed"
  - RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin || echo "tarpaulin already installed"
  - rustup target add wasm32-unknown-unknown --toolchain=nightly
script:
  - make test
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker build -f docker/Dockerfile.ubuntu -t holochain/rust-ubuntu "$@" .; cd ..;
    fi
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD; docker push holochain/rust-ubuntu;
    fi
  - if [ "$TRAVIS_BRANCH" == "develop" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker build -f docker/Dockerfile.ubuntu -t holochain/rust-ubuntu:develop "$@" .;
    cd ..; fi
  - if [ "$TRAVIS_BRANCH" == "develop" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD; docker push holochain/rust-ubuntu:develop;
    fi
