[package]
name = "holochain_core"
version = "0.1.0"
authors = ["Nicolas Luck <nicolas@lucksus.org>",
           "David Meister <thedavidmeister@gmail.com>"]

[dependencies]
holochain_dna = { path = "../dna" }
holochain_agent = { path = "../agent" }
chrono = "0.4"
wasmi = "0.3"
wabt = "0.4"
snowflake = "1.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = { version = "1.0", features = ["preserve_order"] }
multihash = "0.8.0"
rust-base58 = "0.0.4"
